version: "3"
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget-planner-backend
    ports:
      - 3080:3080
    volumes:
      - ./backend:/usr/src/app/backend
  vue-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: budget-planner-frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
